#!/bin/bash -l

( ln -s ../../main/wrf.exe . )
( ln -s ../../main/real.exe . )
( ln -s ../../main/tc.exe . )
( ln -s ../../main/ndown.exe . )
( ln -s ../../run/README.namelist . )
( ln -s ../../run/README.physics_files . )
( ln -s ../../run/README.tslist . )
( ln -sf ../../run/ETAMPNEW_DATA . ;                     \
  ln -sf ../../run/ETAMPNEW_DATA.expanded_rain . ;       \
  ln -sf ../../run/RRTM_DATA . ;                         \
  ln -sf ../../run/RRTMG_LW_DATA . ;                     \
  ln -sf ../../run/RRTMG_SW_DATA . ;                     \
  ln -sf ../../run/CAM_ABS_DATA . ;                      \
  ln -sf ../../run/CAM_AEROPT_DATA . ;                   \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.RCP4.5 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.RCP6   . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.RCP8.5 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.A1B    . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.A2     . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP119 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP126 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP245 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP245 CAMtr_volume_mixing_ratio ;   \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP370 . ;  \
  ln -sf ../../run/CAMtr_volume_mixing_ratio.SSP585 . ;  \
  ln -sf ../../run/CLM_ALB_ICE_DFS_DATA . ;              \
  ln -sf ../../run/CLM_ALB_ICE_DRC_DATA . ;              \
  ln -sf ../../run/CLM_ASM_ICE_DFS_DATA . ;              \
  ln -sf ../../run/CLM_ASM_ICE_DRC_DATA . ;              \
  ln -sf ../../run/CLM_DRDSDT0_DATA . ;                  \
  ln -sf ../../run/CLM_EXT_ICE_DFS_DATA . ;              \
  ln -sf ../../run/CLM_EXT_ICE_DRC_DATA . ;              \
  ln -sf ../../run/CLM_KAPPA_DATA . ;                    \
  ln -sf ../../run/CLM_TAU_DATA . ;                      \
  ln -sf ../../run/ozone.formatted . ;                   \
  ln -sf ../../run/ozone_lat.formatted . ;               \
  ln -sf ../../run/ozone_plev.formatted . ;              \
  ln -sf ../../run/aerosol.formatted . ;                 \
  ln -sf ../../run/aerosol_lat.formatted . ;             \
  ln -sf ../../run/aerosol_lon.formatted . ;             \
  ln -sf ../../run/aerosol_plev.formatted . ;            \
  ln -sf ../../run/eclipse_besselian_elements.dat . ;    \
  ln -sf ../../run/capacity.asc . ;                      \
  ln -sf ../../run/coeff_p.asc . ;                       \
  ln -sf ../../run/coeff_q.asc . ;                       \
  ln -sf ../../run/constants.asc . ;                     \
  ln -sf ../../run/masses.asc . ;                        \
  ln -sf ../../run/termvels.asc . ;                      \
  ln -sf ../../run/kernels.asc_s_0_03_0_9 . ;            \
  ln -sf ../../run/kernels_z.asc . ;                     \
  ln -sf ../../run/bulkdens.asc_s_0_03_0_9 . ;           \
  ln -sf ../../run/bulkradii.asc_s_0_03_0_9 . ;          \
  ln -sf ../../run/CCN_ACTIVATE.BIN . ;                  \
  ln -sf ../../run/p3_lookupTable_1.dat-5.3-2momI . ;    \
  ln -sf ../../run/p3_lookupTable_1.dat-3momI_v5.1.7 . ; \
  ln -sf ../../run/p3_lookupTable_2.dat-2momI_v5.2.3 . ; \
  ln -sf ../../run/HLC.TBL . ;                           \
#  ln -sf ../../run/wind-turbine-1.tbl . ;                \
  ln -sf ../../run/ishmael-gamma-tab.bin . ;             \
  ln -sf ../../run/ishmael-qi-qc.bin . ;                 \
  ln -sf ../../run/ishmael-qi-qr.bin . ;                 \
  ln -sf ../../run/BROADBAND_CLOUD_GODDARD.bin . ;       \
  ln -sf ../../run/STOCHPERT.TBL . ;                     \
  ( cd ../em_real ; if test -d ../../run/SBM_input_33 ; then                   \
    ln -sf ../../run/SBM_input_33 . ;                                          \
    ln -sf ../../run/scattering_tables_2layer_high_quad_1dT_1%fw_110 . ;       \
    fi )
  )
( ln -s ../../run/GENPARM.TBL . )
( ln -s ../../run/LANDUSE.TBL . )
( ln -s ../../run/SOILPARM.TBL . )
( ln -s ../../run/URBPARM.TBL . )
( ln -s ../../run/URBPARM_LCZ.TBL . )
( ln -s ../../run/VEGPARM.TBL . )
( ln -s ../../run/MPTABLE.TBL . )
( ln -s ../../run/tr49t67 . )
( ln -s ../../run/tr49t85 . )
( ln -s ../../run/tr67t85 . )
( ln -s ../../run/gribmap.txt . )
( ln -s ../../run/grib2map.tbl . )

echo -e "========================"
echo -e "symbolic link completed."
echo -e "========================"
